name: 'hello, bird.'
favicon: null
layout_spectrum: 0.23965
typography_spectrum: 0.74609
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#959595'
    - '#8a8a8a'
    - '#808080'
    - '#555555'
    - '#aaaaaa'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
