name: 'hello, bird.'
favicon: null
layout_spectrum: 0.41445140400901437
typography_spectrum: 0.6486852585803717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8440072403755039
  lightness: 0.392810276709497
  saturation: 0.54253746336326
  rhythmicContrast: 0.8562727626413107
purpose: []
