name: 'hello, bird.'
favicon: null
layout_spectrum: 0.49776
typography_spectrum: 0.74609
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#999999'
    - '#ffe4e5'
    - '#cccccc'
    - '#bababa'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
